/*
 * Generated by PWGenPrj
 * Generated at __PWTEMPLATE_DATE__
 */

/*!
 * \file adminchannel.h
 * \brief Admin channel logic
 */

#ifndef ADMINCHANNEL_H
#define ADMINCHANNEL_H

class AdminChannel final : public pw::MsgChannel
{
public:
	using pw::MsgChannel::MsgChannel;
	inline virtual ~AdminChannel() {}

private:
	void eventReadPacket(const pw::PacketInterface& pk, const char*, size_t) override;

public:
	using proc_ptr_t = void (AdminChannel::*)(const pw::MsgPacket& pk);

	void procEXIT(const pw::MsgPacket& pk);
};

#endif // ADMINCHANNEL_H
