/*
 * Generated by PWGenPrj
 * Generated at __PWTEMPLATE_DATE__
 */

/*!
 * \file main.cpp
 * \brief Entry point.
 */

#include "./mycommon.h"

int main(int argc, char* argv[])
{
	return INST.start(argc, argv);
}
