/*
 * Generated by PWGenPrj
 * Generated at __PWTEMPLATE_DATE__
 */

/*!
 * \file mycommon.h
 * \brief Local common header
 */

#ifndef MYCOMMON_H
#define MYCOMMON_H

#include <pw/pwlib.h>

constexpr auto g_name = "__PWTEMPLATE_NAME__";
constexpr auto g_start = "__PWTEMPLATE_DATE__";


// Local headers...
#include "./myinstance.h"

#endif // MYCOMMON_H
