/*
 * Generated by PWGenPrj
 * Generated at __PWTEMPLATE_DATE__
 */

/*!
 * \file mylistener.h
 * \brief Listeners
 */

#ifndef MYLISTENER_H
#define MYLISTENER_H

class ServiceListener final : public pw::ListenerInterface
{
public:
	using pw::ListenerInterface::ListenerInterface;
	inline virtual ~ServiceListener() {}

	inline int getType(void) const override { return LT_SERVICE; }

private:
	bool eventAccept(const accept_type& param) override;
};

class AdminListener final : public pw::ListenerInterface
{
public:
	using pw::ListenerInterface::ListenerInterface;
	inline virtual ~AdminListener() {}

	inline int getType(void) const override { return LT_ADMIN; }

private:
	bool eventAccept(const accept_type& param) override;
};

class ChildListener final : public pw::ChildListenerInterface
{
public:
	using pw::ChildListenerInterface::ChildListenerInterface;
	inline virtual ~ChildListener() {}

private:
	bool eventSetParameters(accept_type& param) override;
	bool eventAccept(const accept_type& param) override;
};

#endif // MYLISTENER_H
